import "@/styles/globals.css"
import { MoralisProvider } from "react-moralis"
import Header from "../components/Header"
import Head from "next/head" //bring this here and delete it from index.js when we bring the Head here

//we add the Header here above Component im assuming so that regardless of the page that we're viewing, the header is always above

//initializeOnMount is false because we're not using the server yet
//we took this Head from index.js that is created there when we do create next app, actually makes a lot more sense for it to be in here, unless im assuming we wanted a different head for each page
export default function App({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MoralisProvider initializeOnMount={false}>
                <Header />
                <Component {...pageProps} />
            </MoralisProvider>
        </div>
    )
}

//Having MoralisProvider (or others) wrapped around our "Component" means that we don't have to pass parameters between our components or pages.
//For example our "LotteryEntrance" will know which chainId we're on because our "Header" is gonna pass it to "MoralisProvider" which is gonna pass to the "LotteryEntrance"
